server:
  port: 9990

spring:
  mustache:
    check-template-location: false
    jpa:
      defer-datasource-initialization: true
    profiles:
      active:
      - redis
      - postgre
  logging:
    level:
      org:
        atmosphere: warn

  vaadin:
    launch-browser: true

    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application


